# docker-compose.yml
#version: '3.8'

services:
  db:
    image: postgres:16-alpine  # Official PostgreSQL
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/mydb
      JWT_SECRET: mysecret

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  postgres_data: