name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        #options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: |
        cd server
        npm install
        cd ../client
        npm install
    
    - name: Run server tests
      env:
        DATABASE_URL: postgres://postgres:test@localhost:5432/testdb
        JWT_SECRET: testsecret
      run: |
        cd server
        npm test
    
    - name: Run client tests
      run: |
        cd client
        CI=true npm test